### PR TITLE
Use correct jax/jaxlib constraints in recipe

### LINKED ISSUE #19: Recipe does not use correct jax/jaxlib constraints
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems like the constraints for jax/jaxlib specified in this feedstock are outdated. They should be updated to reflect the values in `numpyro`'s `setup.py` file, which I think are up to date.

### Installed packages

```shell
#
```

### Environment info

```shell
#
```

cc @fehiepsi

### PR DESCRIPTION
**Pull request by pierreglaser**
Fixes #19 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

cc @fehiepsi

### CODE REVIEW

**Comment by fehiepsi** [comment]
Thanks. Do you think that we should worry about the errors? It looks to me like we need to bump the version number in the checklist.

**Comment by pierreglaser** [comment]
> Thanks. Do you think that we should worry about the errors? It looks to me like we need to bump the version number in the checklist.

Yep correct. Will do that now.

**Comment by pierreglaser** [comment]
> Thanks. Do you think that we should worry about the errors? 

Some of the errors I looked at seemed like random timeout error. Let's look at the results of this CI run.

**Comment by fehiepsi** [comment]
@conda-forge-admin, please rerender

**Comment by fehiepsi** [comment]
Thanks, @pierreglaser!

**Pull request merged**
